name: Auto Translate SRT

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Set up Go
        uses:  actions/setup-go@v6
        with:
          go-version: 'stable'
      
      - name: Install translate-shell
        run: |
          git clone https://github.com/soimort/translate-shell.git
          cd translate-shell
          make
          sudo make install
          trans --version
      - name: test trans success
        run: trans -e google -b en:zh "test"
      - name: Download dependencies
        run: go mod download
      
      - name: Create srt directory if not exists
        run: mkdir -p srt
      
      - name: Run translation program
        run: go run .
        working-directory: ${{ github.workspace }}
      
      - name: Upload translated files as artifact
        uses: actions/upload-artifact@v7
        with:
          name: translated-srt-files
          path: | 
            **/*.srt
          retention-days: 30
